controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    prefix:
#        en: '/en'
#        fr: '/'
#        it: '/it'
    schemes: [http, https]
